version: '3.7'
services:
  web:
    image: jekyll/jekyll:pages
    ports:
      - 4000:4000
    volumes:
      - ${PWD}:/srv/jekyll
    command: jekyll serve --force_polling -d ./docs
    init: true
    tty: true
